Repository BC-MAY-21-ROR/kata-07-reloj-checador-k7-f22-t1, pull requests merged in 2022-03, with the labels that each got.

#8 controller and model were generated
  Gemfile.lock
  app/controllers/branches_controller.rb
  app/helpers/branches_helper.rb
  app/models/branch.rb
  db/migrate/20220308233900_create_branches.rb
  test/controllers/branches_controller_test.rb
  test/fixtures/branches.yml
  test/models/branch_test.rb
Labels: review required

#13 The database was changed
  .gitignore
  Gemfile
  Gemfile.lock
  config/database.yml.example
  db/schema.rb
Labels: ready for review

#11 3 employes crud
  app/channels/application_cable/channel.rb
  app/channels/application_cable/connection.rb
  app/controllers/application_controller.rb
  app/controllers/employees_controller.rb
  app/helpers/application_helper.rb
  app/helpers/employees_helper.rb
  app/jobs/application_job.rb
  app/mailers/application_mailer.rb
  app/models/application_record.rb
  app/models/employee.rb
  app/views/employees/edit.html.erb
  app/views/employees/index.html.erb
  app/views/employees/new.html.erb
  config/routes.rb
  db/migrate/20220308000348_create_employees.rb
Labels: mentor review required, review required

#17 bootstrap was added to the project
  .gitignore
  Gemfile
  Gemfile.lock
  Procfile.dev
  app/assets/builds/.keep
  app/assets/config/manifest.js
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/application.css
  app/assets/stylesheets/application.sass.scss
  app/javascript/application.js
  bin/dev
  config/initializers/assets.rb
  package.json
  yarn.lock
Labels: mentor review required, ready for review, review required

#14 Design proposal completed
  design/Desktop - Add Branches.png
  design/Desktop - Add Employee.png
  design/Desktop - Admin Branches.png
  design/Desktop - Admin Login.png
  design/Desktop - Admin Main.png
  design/Desktop - Branch Reports - Absence by month.png
  design/Desktop - Branch Reports - Attendance by day.png
  design/Desktop - Branch Reports - Attendance by month.png
  design/Desktop - Check-in-out.png
  design/Desktop - Edit branch.png
Labels: ready for review

#25 21 main view branch section
  app/assets/stylesheets/_button_colors.sass.scss
  app/assets/stylesheets/_variables.sass.scss
  app/assets/stylesheets/application.sass.scss
  app/controllers/branches_controller.rb
  app/javascript/application.js
  app/javascript/controllers/branches_controller.js
  app/models/branch.rb
  app/views/branches/_branch.html.erb
  app/views/branches/_form.html.erb
  app/views/branches/edit.html.erb
  app/views/branches/index.html.erb
  app/views/branches/new.html.erb
  app/views/branches/show.html.erb
  db/schema.rb
  package.json
  yarn.lock
Labels: ready for review

#24 20 admin main view
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/_variables.scss
  app/assets/stylesheets/application.sass.scss
  app/assets/stylesheets/employees/box.scss
  app/assets/stylesheets/employees/button.scss
  app/assets/stylesheets/employees/form.scss
  app/assets/stylesheets/records/check.scss
  app/controllers/employees_controller.rb
  app/models/employee.rb
  app/views/employees/_form.html.erb
  app/views/employees/edit.html.erb
  app/views/employees/index.html.erb
  app/views/employees/new.html.erb
  app/views/records/new.html.erb
  config/routes.rb
  db/migrate/20220308000348_create_employees.rb
  db/schema.rb
Labels: mentor review required, ready for review

#29 19 elaboration of navbar and clock
  app/assets/stylesheets/_button_colors.sass.scss
  app/assets/stylesheets/_check_form.sass.scss
  app/assets/stylesheets/_clock.sass.scss
  app/assets/stylesheets/_navbar.sass.scss
  app/assets/stylesheets/_variables.sass.scss
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/application.sass.scss
  app/controllers/employees_controller.rb
  app/javascript/controllers/clock_controller.js
  app/javascript/controllers/hello_controller.js
  app/views/branches/index.html.erb
  app/views/employees/index.html.erb
  app/views/layouts/application.html.erb
  app/views/records/new.html.erb
  app/views/shared/_navigation.html.erb
  config/routes.rb
  db/migrate/20220308000348_create_employees.rb
  db/migrate/20220311235447_create_records.rb
  db/migrate/20220324214617_references.rb
  db/schema.rb
Labels: ready for review

#30 28 add branch reports view attendance by day window
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/_button_colors.sass.scss
  app/assets/stylesheets/application.sass.scss
  app/assets/stylesheets/branches/show.scss
  app/assets/stylesheets/branches/titles.scss
  app/controllers/branches_controller.rb
  app/controllers/employees_controller.rb
  app/controllers/records_controller.rb
  app/helpers/branches_helper.rb
  app/helpers/employees_helper.rb
  app/models/employee.rb
  app/models/record.rb
  app/views/branches/_attendance.html.erb
  app/views/branches/_branch.html.erb
  app/views/branches/_filter.html.erb
  app/views/branches/show.html.erb
  app/views/branches/show.json.jbuilder
  config/routes.rb
  lib/tasks/data.rake
Labels: mentor review required, review required
